version: "3.1"
services:
  dns-doh:
    container_name: cloudflared
    image: crazymax/cloudflared
    restart: always
    networks:
      dns-doh-net:
        ipv4_address: 172.23.0.2

  dnsmasq:
    container_name: dnsmasq
    image: 4km3/dnsmasq:2.85-r2
    cap_add:
      - NET_ADMIN
    command: ["--no-resolv", "--domain-needed", "--server=172.23.0.2#5053"]
    networks:
      dns-doh-net:
        ipv4_address: 172.23.0.3
      guest-net:
        ipv4_address: 172.24.0.2
    restart: always
    depends_on:
      - dns-doh

  tor:
    image: osminogin/tor-simple
    networks:
      guest-net:
        ipv4_address: 172.24.0.4
    restart: always
    dns: 172.24.0.2
    depends_on:
      - dnsmasq

  l0pht:
    container_name: l0pht-host
    build: host
    depends_on:
      - dnsmasq
    restart: always
    dns: 255.255.255.255
    ports:
      - "2222:2222"
    volumes:
      - "~/l0pht/cfg/etc/ssh:/etc/ssh/l0pht:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

# init: true
# secrets:

# volumes:
#   guest-data:
#     type: bind
#     - driver: local
#     device: ~/research/l0pht/guest/l0pht-guest
#     external: true

networks:
  dns-doh-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

  guest-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24

