version: "3.7"
services:
  dns-doh:
    image: crazymax/cloudflared
    restart: always
    networks:
      dns-doh-net:
        ipv4_address: 172.23.0.2

  dnsmasq:
    image: 4km3/dnsmasq:2.85-r2
    cap_add:
      - NET_ADMIN
    command: ["--no-resolv", "--domain-needed", "--server=172.23.0.2#5053", "--server=/onion/10.11.255.251#5353"]
    networks:
      dns-doh-net:
        ipv4_address: 172.23.0.3
      guest-net:
        ipv4_address: 10.11.255.252
    restart: always
    depends_on:
      - dns-doh

  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    depends_on:
      - dnsmasq
    dns: 172.23.0.3 #dnsmasq on dns-doh-net
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY=${SF_NORDVPN_PRIVATE_KEY:-}
      - POST_UP=/sf/bin/vpn_wg2status.sh /sf/run/vpn/status-nordlynx.log post_up %i
      - POST_DOWN=/sf/bin/vpn_wg2status.sh /sf/run/vpn/status-nordlynx.log post_down %i
    networks:
      vpn:
        ipv4_address: 172.20.0.254
      dns-doh-net:
        ipv4_address: 172.23.0.254
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    volumes:
      - "${SF_RUNDIR:-/dev/shm/sf/vpn}:/sf/run/vpn"
      - "${SF_BASEDIR:-.}/sfbin:/sf/bin:ro"

  router:
    build: router
    image: sf-router
    depends_on:
      - router-fix-network
    networks:
      vpn:
        ipv4_address: 172.20.0.2
      guest-net:
        ipv4_address: 10.11.255.253 # Will be replaced by init.sh with 10.11.0.1
    cap_add:
      - NET_ADMIN
    environment:
      - SF_DEBUG=${SF_DEBUG:-}
      - SF_MAXOUT=${SF_MAXOUT:-}
      - SF_MAXIN=${SF_MAXIN:-}
    volumes:
      - "${SF_BASEDIR:-.}/config/etc/tc:/config/tc:ro"
    entrypoint: ["/init.sh"]

  router-fix-network:
    image: sf-router
    network_mode: host # host's stack
    cap_add:
      - NET_ADMIN
    environment:
      - SF_DEBUG=${SF_DEBUG:-}
    entrypoint: ["/fix-network.sh"]

  tor:
    build: tor
    image: sf-tor
    networks:
      guest-net:
        ipv4_address: 10.11.255.251
      nginx-net:
    cap_add:
      - NET_ADMIN    
    restart: always
    dns: 10.11.255.252
    depends_on:
      - dnsmasq
      - nginx
    volumes:
      - "${SF_BASEDIR:-.}/config/${SF_FQDN:-SF_FQDN-NOT-SET.hack.segfault.net}/tor/hidden_service:/var/lib/tor/hidden_service"
      - "${SF_BASEDIR:-.}/config/etc/tor:/config/tor:ro"

  segfault:
    build: host
    image: sf-host
    # /bin/segfaultsh need to know the container name; set it to sf-host statically
    container_name: sf-host
    depends_on:
      - dnsmasq
    restart: always
    init: true
    dns: 255.255.255.255
    # SSHD clears all environment variables before spwaning a shell (segfaultsh).
    # Add any variables to docker_sshd.sh as well.
    environment:
      - SF_DNS=${SF_DNS:-10.11.255.252}
      - SF_BASEDIR=${SF_BASEDIR}
      - SF_RUNDIR=${SF_RUNDIR:-/dev/shm/sf}
      - SF_USER=${SF_USER:-root}
      - SF_USER_PASSWORD=${SF_USER_PASSWORD:-segfault}
      - SF_FQDN=${SF_FQDN:-SF_FQDN-NOT-SET.hack.segfault.net}
      - SF_ENCFS_SECDIR=${SF_ENCFS_SECDIR:-/dev/shm/encfs-sec}
      - SF_DEBUG=${SF_DEBUG:-}
    ports:
      - "${SF_SSH_PORT:-22}:2222"
    volumes:
      - "${SF_BASEDIR:-.}/config/etc/ssh:/config/etc/ssh"
      - "${SF_BASEDIR:-.}/config/db:/config/db"
      - "${SF_ENCFS_SECDIR:-/dev/shm/encfs-sec}/onion-www:/onion:slave"
      - "/var/run/docker.sock:/var/run/docker.sock"

  nginx-encfs:
    build: encfs
    image: sf-encfs
    restart: always
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - SF_ENCFS_PASS
    command: ["/mount.sh", "server"]
    network_mode: none
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - "${SF_BASEDIR:-.}/config/etc/encfs:/config"
      - "${SF_BASEDIR:-.}/data/onion-www:/encfs/raw"
      - "${SF_ENCFS_SECDIR:-/dev/shm/encfs-sec}/onion-www:/encfs/sec:shared"

  nginx:
    image: nginx
    restart: always
    depends_on:
      - nginx-encfs
    dns: 255.255.255.255
    # ports:
    #   - 8080:80 # FIXME: testing..
    networks:
      nginx-net:
    volumes:
      - "${SF_ENCFS_SECDIR:-/dev/shm/encfs-sec}/onion-www:/srv/www:slave,ro"
      - "${SF_BASEDIR:-.}/config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24

  nginx-net:
    driver: bridge

  dns-doh-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

  # User's shell
  guest-net:
    name: sf_guest-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/16
        # default gw is always 10.11.0.1 and is the host side of the bridge (?)

