version: "3.7"
services:
  dns-doh:
    container_name: cloudflared
    image: crazymax/cloudflared
    restart: always
    networks:
      dns-doh-net:
        ipv4_address: 172.23.0.2

  dnsmasq:
    container_name: dnsmasq
    image: 4km3/dnsmasq:2.85-r2
    cap_add:
      - NET_ADMIN
    command: ["--no-resolv", "--domain-needed", "--server=172.23.0.2#5053"]
    networks:
      dns-doh-net:
        ipv4_address: 172.23.0.3
      guest-net:
        ipv4_address: 172.24.0.2
    restart: always
    depends_on:
      - dns-doh

  tor:
    image: osminogin/tor-simple
    container_name: sf-tor
    networks:
      guest-net:
        ipv4_address: 172.24.0.4
    restart: always
    dns: 172.24.0.2
    depends_on:
      - dnsmasq

  segfault:
    container_name: sf-host
    build: host
    depends_on:
      - dnsmasq
    restart: always
    init: true
    dns: 255.255.255.255
    ports:
      - "${PORT}:2222"
    env_file:
      .env
    volumes:
      - "${SF_BASEDIR}/config:/config:ro"
      - "${SF_BASEDIR}/config/db:/config/db"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  dns-doh-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

  guest-net:
    name: sf_guest-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24

